### ISSUE TITLE
Add Refresh functionality to Home button

### ISSUE THREAD

**Issue by mohitvdx** [Vikash-8090-Yadav/SaL--dApp#117]
This is a follow up issue from issue #71 

As requested by @Vikash-8090-Yadav  the **Home** button on the landing page Navigation bar should **refresh** the page

**Comment by capsy14** [comment]
Please assign me this issue #117 Add Refresh functionality to Home button

**Comment by Vikash-8090-Yadav** [comment]
yah @mohitvdx but why u created the another issue 4 this ?

**Comment by mohitvdx** [comment]
@Vikash-8090-Yadav  hi I was having some difficulty in it. So I created the issue for someone else to do

**Comment by Vikash-8090-Yadav** [comment]
oh got it.

**Comment by Vikash-8090-Yadav** [comment]
Hey @capsy14 Start working on this.
