### ISSUE TITLE
Image bar looks wired

### ISSUE THREAD

**Issue by 9520prashant** [Vikash-8090-Yadav/SaL--dApp#120]
When a new user go to side then image bar looks wired sometime, the size of that is very big. You can see in Screen Shot it has covered a part of cards.

![Screenshot (253)](https://github.com/Vikash-8090-Yadav/SaL--dApp/assets/99237795/8911a721-c943-41d7-9344-f056b61c434a)

Hey @Vikash-8090-Yadav I am a contributor at GSSOC. kindly assign me this issue.

**Comment by 9520prashant** [comment]
Improvement we should do:   

![Screenshot (254)](https://github.com/Vikash-8090-Yadav/SaL--dApp/assets/99237795/2c71d627-85c8-4fc3-8b1e-19aa978ea8d8)

**Comment by Vikash-8090-Yadav** [comment]
Hey, this widget is from the arcana. As of now, it's impossible to change this UI. If you find anything then feel free to open this issue. Thanks!

**Comment by 9520prashant** [comment]
Ohh OK

**Comment by 9520prashant** [comment]
@Vikash-8090-Yadav One more issue i found that is footer do not have links of any social can i create a new issue and start working on it

**Comment by Vikash-8090-Yadav** [comment]
Currently Sal Dapp has not on any social media . Thats y. In future will add this .Thaks uh!

**Comment by 9520prashant** [comment]
Sure
