### ISSUE TITLE
social link not working

### ISSUE THREAD

**Issue by engorgedspirit** [Vikash-8090-Yadav/SaL--dApp#130]
![image](https://github.com/Vikash-8090-Yadav/SaL--dApp/assets/85272049/537a2ae1-b698-4bbc-a7b3-79244b1ecd42)
these links are not workin
Im a GSSoc cntributor, please assign me this issue, I will resolve it

**Comment by Vikash-8090-Yadav** [comment]
currently am not looking for this . Thanks !
