### ISSUE TITLE
bottom logo

### ISSUE THREAD

**Issue by engorgedspirit** [Vikash-8090-Yadav/SaL--dApp#132]
![image](https://github.com/Vikash-8090-Yadav/SaL--dApp/assets/85272049/26e432ae-24bd-446c-9847-db3f08393c81)
looks ugly, needs to fix this
Im a GSSoc cntributor, please assign me this issue, I will resolve it

**Comment by Vikash-8090-Yadav** [comment]
Sorry bro, but this UI is from Arcana. and is inbuilt u can't   improve this .
