### ISSUE TITLE
Wants to improve button, card

### ISSUE THREAD

**Issue by ojasaklechayt** [Vikash-8090-Yadav/SaL--dApp#147]
### What would you like to share?

Improved Styling of Navbar, Cards in the homepage after logging in.

1. Improved Logout button position
2. Improved card design

**Comment by Umesh7Dixit** [comment]
I want to improve button can u please assign me this issue

**Comment by roshangeorge97** [comment]
@ojasaklechayt please create a PR, we will look into merging!

**Comment by ojasaklechayt** [comment]
@roshangeorge97 okay also can you please assign this under gssoc ?
