### ISSUE TITLE
[feat] Redesign the Footer 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/SaL--dApp#159]
### Would you like to have a new feature? Please describe.

I am looking  some dev who can redesign the Footer completely a/c to the design provided .
The design is in design folder present inside the root. 
Write code for navbar in Component/v1.0.0/footer

Note: Please visit to V1.0.0 branch and make that changes into that branch only and push changes into v1.0 0 branch only not in main branch.
All the communication regarding the designing part will done  in Discord only.

### Additional context

Deadline: Within 5 days of assigned.

**Comment by coder12git** [comment]
@Vikash-8090-Yadav Please assign me this issue.
I am in GSSOC'23

**Comment by Vikash-8090-Yadav** [comment]
> @Vikash-8090-Yadav Please assign me this issue.
> I am in GSSOC'23

Sure, start working on this.

**Comment by coder12git** [comment]
Thanks

**Comment by coder12git** [comment]
I have created a PR for this today.

**Comment by Vikash-8090-Yadav** [comment]
> I have created a PR for this today.

PR NO?
