### ISSUE TITLE
Overlapping of Select Profile section.

### ISSUE THREAD

**Issue by BaibhavTiwari** [Vikash-8090-Yadav/SaL--dApp#16]
The Profile section overlaps the Navbar when it reach to the same height as you can see from the screen shot.
> Screen Shot :
><img src ="https://user-images.githubusercontent.com/75496387/227844932-367165b9-dbe8-4405-b698-b3389bdc2304.png" width="500">

**Comment by Vikash-8090-Yadav** [comment]
Great issue @BaibhavTiwari . Start working on it !!

**Comment by BaibhavTiwari** [comment]
Sure @Vikash-8090-Yadav 🚀

**Comment by BaibhavTiwari** [comment]
**hey @Vikash-8090-Yadav  will like to edit the styling of the navbar and the Select Profile button and the index page to look something like :**

>Select Profile button and Index Page:
><img src="https://user-images.githubusercontent.com/75496387/228290125-fbdfb334-9cfb-4829-a06e-4223a338a660.png" width ="400">

>Navbar : [just changed the padding size and added a dark background color]
><img src="https://user-images.githubusercontent.com/75496387/228299259-ea2747d0-f562-4afc-9820-f327ca92fe72.png" width="700">
>Original :
><img src="https://user-images.githubusercontent.com/75496387/228300202-6fd29849-dc92-4038-b74c-5d8e5aec2564.png" width="700">

**Comment by Vikash-8090-Yadav** [comment]
@BaibhavTiwari please share a  video for   changes .

**Comment by BaibhavTiwari** [comment]
> @BaibhavTiwari please share a video for changes .

you can see the changes here : https://www.loom.com/share/e57b344eadfd4e24b0a5d1a042b9ac8b

**Comment by Vikash-8090-Yadav** [comment]
Great raise a pr for this
