### ISSUE TITLE
Centering Help Section on the page [GSSOC'23]

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Vikash-8090-Yadav/SaL--dApp#162]
### Describe the bug

The help section is not centered it is left aligned

### Expected Behavior

The help section will be centerred on the page

### Screenshot/ Video

![image](https://github.com/Vikash-8090-Yadav/SaL--dApp/assets/85278243/c3b2827a-531c-4f17-bbde-60bb06cfc6cd)

**Comment by Swapnil-Singh-99** [comment]
@rrsingh11 Yes Please

**Comment by Swapnil-Singh-99** [comment]
@Vikash-8090-Yadav @rrsingh11 

Sir I am getting error while running the app.

## Error Screenshot
![image](https://github.com/Vikash-8090-Yadav/SaL--dApp/assets/85278243/26dd916b-c568-4b21-b665-17a87e970e33)
![image](https://github.com/Vikash-8090-Yadav/SaL--dApp/assets/85278243/56f43016-9644-4f13-a396-f6b97254f999)

## Process of starting app
`npm install`
`npm run dev`

Browser - `Chrome` `Firefox`

Please help me regarding this I am not able to run the Web App locally.

**Comment by Vikash-8090-Yadav** [comment]
Msg in  discord.
