### ISSUE TITLE
[feat] : Create a Contact Form 

### ISSUE THREAD

**Issue by Hemant2335** [Vikash-8090-Yadav/SaL--dApp#174]
### Would you like to have a new feature? Please describe.

As of now when we click on the Contact Form we are lead to homepage only , then i would like to create you one contact form

-> I will be creating the frontend 
-> If you want  , I can create the backend too in another issue
-> Also it will be completely responsive 
-> If you have any designs then please suggest.

### How would this feature be beneficial for the project

This feature will grant user to contact with the admin if any issue arises with the website .

### Additional context

Please assign this issue to me under gssoc'23

**Comment by Vikash-8090-Yadav** [comment]
I don't think so there's need  of this currently!
