### ISSUE TITLE
[feat]Redesign About section

### ISSUE THREAD

**Issue by coder12git** [Vikash-8090-Yadav/SaL--dApp#179]
### Would you like to have a new feature? Please describe.

I want to redesign the About section according to the designs provided !!
https://www.figma.com/proto/iAFIUE69Xk45BV3WEi2ilR/Sal-Dapp?type=design&node-id=6-61&scaling=scale-down-width&page-id=6%3A59&starting-point-node-id=6%3A61

**Comment by Vikash-8090-Yadav** [comment]
Great. Start working on this.

**Comment by coder12git** [comment]
> Owner

Thanks

**Comment by coder12git** [comment]
> Great. Start working on this.

@Vikash-8090-Yadav Created a PR for this today!
PR No - #182
