### ISSUE TITLE
UI: Current selected Menu Item Doesn't get highlighted in bold

### ISSUE THREAD

**Issue by Oitanny** [Vikash-8090-Yadav/SaL--dApp#18]
![image](https://user-images.githubusercontent.com/85064763/228047243-4aff7e4e-3a6a-46f3-8aa9-8a16ba1e526e.png)

Whenever a user clicks on some other menu item, for eg settings, contract balance etc, it doesn't get highlighted with bold.

**Comment by Vikash-8090-Yadav** [comment]
start working on this @Oitanny

**Comment by Chinmay-Deo-2004** [comment]
@Oitanny  Do you need help with generating the pull request? What seems to be the issue?

**Comment by Arioum** [comment]
Hey @Vikash-8090-Yadav could you assign me this, I am almost ready with the solution.

**Comment by Vikash-8090-Yadav** [comment]
> Hey @Vikash-8090-Yadav could you assign me this, I am almost ready with the solution.

@Chinmay-Deo-2004 ??

**Comment by Arioum** [comment]
Hey @Vikash-8090-Yadav while we wait for @Oitanny I need your input on this:

I have added new icons for the rest of sidenav items which were using the placeholder icon of  "settings.png". And these new icons are imported from react-icons. However I noticed the other ones are imported from assets and are of "png" type. I'd suggest to go with SVG as it will be optimal when we want to change colors (during dark/light mode). As we are already using react-icons, I'd suggest to go with the closest one that resembles the PNG.

I'd like to be ready in case @Oitanny is unavailable.

**Comment by Vikash-8090-Yadav** [comment]
Ya sure.   am waiting for the @Oitanny  reply. And coming to the icon's part, go with the react inbuilt icon only and if possible clean the assets folder also. 
Thanks. 
Ps : ANd for the dark and white mode the icon should be placed in the sidebar only.  So if in case @Oitanny is not available make the icon for the dark and white mode also.

**Comment by Arioum** [comment]
Alright! Thanks for your input!

**Comment by Arioum** [comment]
Hey @Vikash-8090-Yadav , I feel like we can go ahead with my solution. I'll send in a PR, you can assign me this issue.
