### ISSUE TITLE
[feat]Redesign the Problem Solved 

### ISSUE THREAD

**Issue by coder12git** [Vikash-8090-Yadav/SaL--dApp#183]
### Would you like to have a new feature? Please describe.

I want to redesign the problem-solved part on the home page according to the designs provided.

https://www.figma.com/proto/iAFIUE69Xk45BV3WEi2ilR/Sal-Dapp?type=design&node-id=6-61&scaling=scale-down-width&page-id=6%3A59&starting-point-node-id=6%3A61

I am a contributor in GSSOC'23.

**Comment by Vikash-8090-Yadav** [comment]
Great, start working on this.

**Comment by coder12git** [comment]
> Great, start working on this.

Thanks
