### ISSUE TITLE
[bug] Menu page loading 

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Vikash-8090-Yadav/SaL--dApp#189]
### Describe the bug

Each time I click on any menu button the page loads with a new link and appear from the top

### Expected Behavior

The page should load from were the menu is present it should not load from top

### Screenshot/ Video

https://github.com/Vikash-8090-Yadav/SaL--dApp/assets/85278243/6d84936b-29c8-45e0-b4b9-7f2d01eb7e9e

### Additional context

Please assign me this issue so that I can work on this

**Comment by Vikash-8090-Yadav** [comment]
Great, start working on this.
