### ISSUE TITLE
[docs] - There are 6 back to top buttons in the readme, create only one badge "back to top"

### ISSUE THREAD

**Issue by 1Shubham7** [Vikash-8090-Yadav/SaL--dApp#202]
### Category of documentation update

![image](https://github.com/Vikash-8090-Yadav/SaL--dApp/assets/116020663/9d2d652e-c61f-4f9d-831d-78a9066b26e9)
![image](https://github.com/Vikash-8090-Yadav/SaL--dApp/assets/116020663/ff4ec02e-e634-4d0f-a695-b70e96dc4b86)
![image](https://github.com/Vikash-8090-Yadav/SaL--dApp/assets/116020663/4e32db47-994c-4fbf-9e3c-fa41f15164a8)

There are 6 of them. We already have a table of content for navigation purposes, I want to edit them out and create on badge for "back to  top" instead of text at the end of the page

### Describe the change you think might work

 I want to edit them out and create on badge for "back to  top" instead of text at the end of the page

**Comment by Vikash-8090-Yadav** [comment]
Great start working on this/
