### ISSUE TITLE
changing class to className attribute for react in lft.js file

### ISSUE THREAD

**Issue by Arioum** [Vikash-8090-Yadav/SaL--dApp#24]
**lft.js requires the following fix to get rid of warnings:**

The class attribute is equivalent to className as it is advised in react. Missing alt attributes for the images.

_Path for the concerned file: 
**SaL--dApp\Component\lft.js**_

**Comment by Arioum** [comment]
I have raised my PR #25

**Comment by Vikash-8090-Yadav** [comment]
Hey @Arioum  . Thanks for opening this issue, but I guess there is no use for this component which is lft.js .. instead of this u can find the component which is not of use just by checking the layout.js and deleting them. 
Thanks !

**Comment by Arioum** [comment]
Greetings! I have removed 2 component files:- 
-lft.js
-rht.js

**Comment by Arioum** [comment]
I have closed this issue on account of successful PR #25 merge which resolves this issue
