### ISSUE TITLE
to change the footer

### ISSUE THREAD

**Issue by sandeep0009** [Vikash-8090-Yadav/SaL--dApp#32]
issues in the footer section are:
there is no spacing between the text form and button
button is not rounded
text form outline is not none thats why showing border.
changes to be made in copyright too.
im raising these issues please assign it to me

**Comment by Vikash-8090-Yadav** [comment]
can u please share the ss for the same with the improvement

**Comment by sandeep0009** [comment]
<img width="495" alt="image" src="https://github.com/Vikash-8090-Yadav/SaL--dApp/assets/63727946/3df1f706-516f-422f-97fe-27438cb203e9">
this what im talking about this need to be fixed

**Comment by Vikash-8090-Yadav** [comment]
Hey bro, Thanks for opening the issue. But for now  i am not looking to any enhancement for this .

**Comment by sandeep0009** [comment]
hey bro can u assign me this i want to work upon this one
