### ISSUE TITLE
[UPDATE] Enhancing Header with better UI and changing Banner image in Homepage

### ISSUE THREAD

**Issue by himanshu-03** [Vikash-8090-Yadav/SaL--dApp#33]
Hello!
I am Himanshu Agarwal, a proud contribtuor at GSSoC '23. I would like to the contribute to this project by enhancing the header with better UI and animated buttons.

Things I will be doing as of now:
- [ ] Enhancing Header and making it fit with the theme
- [ ] Adding Animated buttons with logos
- [ ] Adding a more clearer and suitable image in the banner of Homepage

@Vikash-8090-Yadav If you think it is legit then do assign me the issue under GSSoC '23 with the level of the PR as well ✌️

**Comment by Vikash-8090-Yadav** [comment]
Yah sure , start working on this . Please let  me know which banner or image are u going to use!

**Comment by himanshu-03** [comment]
> Yah sure , start working on this . Please let me know which banner or image are u going to use!

It would be great if you add the labels and the level of PR's as well

**Comment by Vikash-8090-Yadav** [comment]
Yah bro, if i get any info abt labels from gssoc then i will surely

**Comment by himanshu-03** [comment]
The help section is a little out of the theme. 
Do you want me to work on that too?
I can work on that as well but its gonna take time as there are many tasks to be resolved.

**Comment by Vikash-8090-Yadav** [comment]
> The help section is a little out of the theme. Do you want me to work on that too? I can work on that as well but its gonna take time as there are many tasks to be resolved.

Raise a new issue for this and share the ss.

**Comment by himanshu-03** [comment]
> > The help section is a little out of the theme. Do you want me to work on that too? I can work on that as well but its gonna take time as there are many tasks to be resolved.
> 
> Raise a new issue for this and share the ss.

Okay so you will be assigning me that in another issue?

**Comment by Vikash-8090-Yadav** [comment]
Yup

**Comment by himanshu-03** [comment]
Will that be okay if I Contrbute to this by first week of June as my End Sems are starting from tomorrow.
