### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by Ayushhgupta39** [Vikash-8090-Yadav/SaL--dApp#38]
I want to update the "How to run locally" section in the readme.md.
<img width="283" alt="image" src="https://github.com/Vikash-8090-Yadav/SaL--dApp/assets/96309609/385fc9e3-f32f-4f61-b51e-4c95547c150e">

These shell commands should be properly written and aligned so that it is easier for the readers to understand and comprehend. Please assign me this issue.

**Comment by Vikash-8090-Yadav** [comment]
Please tell me in brief what u want to do ?

**Comment by Ayushhgupta39** [comment]
I want to elaborate this section a bit more and align it properly, so that it looks more readable to the eyes like the rest of the document.

**Comment by Vikash-8090-Yadav** [comment]
Great start working on this

**Comment by Ayushhgupta39** [comment]
The issue has been resolved.
