### ISSUE TITLE
Pr and Issue template

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/SaL--dApp#39]
[For GSSOC'23 Contributors]

Create a pr and issue template.
For reference check this https://github.com/Vikash-8090-Yadav/Future.WebNet

**Comment by hindu-muppala** [comment]
@Vikash-8090-Yadav ,I can able to solve can you assign this issue to me?

**Comment by prathamkumarjha** [comment]
can you assign this issue to me i am pretty confident i can do this

**Comment by SakshiShah29** [comment]
I would like to work on this issue. Please assign it to me under GSSoC'23.

**Comment by Vikash-8090-Yadav** [comment]
Hey @SakshiShah29 as @prathamkumarjha requested first so i have to assign him. Don't worry there are lot's thing to do

**Comment by sagnik-p** [comment]
This issue has been inactive for a long time
I would like to work on this issue
Please assign

**Comment by Vikash-8090-Yadav** [comment]
@hindu-muppala is this done ? Or u raised the PR?

**Comment by Vikash-8090-Yadav** [comment]
@hindu-muppala is this done ? Or u raised the PR?

**Comment by hindu-muppala** [comment]
Yaa, this is done.I think you merged it also.
