### ISSUE TITLE
[STYLE] Styling the Help Section 

### ISSUE THREAD

**Issue by himanshu-03** [Vikash-8090-Yadav/SaL--dApp#42]
Hello!
I am Himanshu Agarwal, a proud contribtuor at GSSoC '23. I would like to the contribute to this project by styling the help section on the homepage.

Things I will be doing as of now:
- [ ] Styling the help section in homepage

@Vikash-8090-Yadav If you think it is legit then do assign me the issue under GSSoC '23 with the level of the PR as well ✌️

**Comment by Vikash-8090-Yadav** [comment]
Great start working on this .

**Comment by himanshu-03** [comment]
Will that be okay if I Contrbute to this by first week of June as my End Sems are starting from tomorrow.

**Comment by Vikash-8090-Yadav** [comment]
> Will that be okay if I Contribute to this by first week of June as my End Sems are starting from tomorrow.

Yah no issue.
