### ISSUE TITLE
Improve Navbar

### ISSUE THREAD

**Issue by kailashchoudhary11** [Vikash-8090-Yadav/SaL--dApp#48]
The Home and the Data navlink are doing the same thing. Also we can link the logo to home such that whenever user clicks on Logo they are redirected to `https://sa-l-d-app.vercel.app/`

**Comment by SakshiShah29** [comment]
I would like to work on this issue. Please assign it to me under GSSoC'23.

**Comment by kailashchoudhary11** [comment]
> If possible share the video or image .

You can test this by clicking on the `Data` link and `Home` link on the Navbar.

**Comment by Vikash-8090-Yadav** [comment]
is this same as ur issue if yes tell me so  that i can re assign that p person.  #71

**Comment by kailashchoudhary11** [comment]
Yes, It is same. You can assign it to me as I raised the issue first.

**Comment by Vikash-8090-Yadav** [comment]
really sorry bro that issue is merged and closed . Please after next time don't forget to chk if someone is trying to take ur issue or not.
