### ISSUE TITLE
Re-design SAL-DAPP homepage in Figma

### ISSUE THREAD

**Issue by Arioum** [Vikash-8090-Yadav/SaL--dApp#55]
**<h3>I'd like to propose a new design for Sal-Dapp Homepage/Dashboard</h3>**

It's also my suggestion to separate the dashboard part to a new '/dashboard' route away from the main landing page.

Tasks:
- [x] Design Landing Page in Figma

I'd like to be assigned to this issue as a part of GSSoC'23

**Comment by Vikash-8090-Yadav** [comment]
Hey bro, You will only design or u  will do the coding part also. ? please do let me know about this .

**Comment by Arioum** [comment]
I can do both Design and Development. We can do this in phases as it might take time.

So first task would be to design and the second would be to develop.

**Comment by Vikash-8090-Yadav** [comment]
Great

**Comment by dhrumishah** [comment]
> I can do both Design and Development. We can do this in phases as it might take time.
> 
> So first task would be to design and the second would be to develop.

hey! what's the update on this? I would like to revamp the website (coding part)

**Comment by Vikash-8090-Yadav** [comment]
> > I can do both Design and Development. We can do this in phases as it might take time.
> > So first task would be to design and the second would be to develop.
> 
> hey! what's the update on this? I would like to revamp the website (coding part)

You can see the newly made issue for the re designing part.
