### ISSUE TITLE
Improving the README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [Vikash-8090-Yadav/SaL--dApp#58]
I would like to be assigned for GSSOC'23 for this issue

Suggestions:
+ Restructuring the header for a more visually appealing look
+ formatting text in a better manner
+ SEO friendly changes to link and text
+ adding badges for a cool effect
+ other minor changes

**Comment by Vikash-8090-Yadav** [comment]
Great. I already passed ur pr. Best of luck .
