### ISSUE TITLE
add readme badges

### ISSUE THREAD

**Issue by S-ishita** [Vikash-8090-Yadav/SaL--dApp#60]
I want to add readme badges .Please assign this issue to me under GSSOC
![badges](https://github.com/Vikash-8090-Yadav/SaL--dApp/assets/104543751/39d07f25-2d43-4430-943d-678fe282b929)

**Comment by Vikash-8090-Yadav** [comment]
Hey thanks but this issue was already raised by someone. You can check this #59

**Comment by Vikash-8090-Yadav** [comment]
Feel free to open this issue if u any other thing to ask.
