### ISSUE TITLE
Spelling mistake in readme. 

### ISSUE THREAD

**Issue by mohitvdx** [Vikash-8090-Yadav/SaL--dApp#66]
**Tailwind** spelled wrong in technology used section.

**Comment by Vikash-8090-Yadav** [comment]
If possible share  the ss of the para and highlight the wrong  word. Along with improvement .

**Comment by mohitvdx** [comment]
yes sure.
<img width="1040" alt="Screenshot 2023-05-22 at 4 05 20 PM" src="https://github.com/Vikash-8090-Yadav/SaL--dApp/assets/112820522/14ad649d-2d31-4d61-9a03-0c4b328feee9">

It should be tailwind instead. I've already solved the issue should I raise a PR?

**Comment by Vikash-8090-Yadav** [comment]
Thanks @CaptainJack2491 .
