### ISSUE TITLE
Improve the Ui of the buy me coffee as well Happy Client Works

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/SaL--dApp#7]
Try to improve the  UI and make  it responsive

**Comment by Bhavika-14** [comment]
@Vikash-8090-Yadav please assign this issue to me

**Comment by Vikash-8090-Yadav** [comment]
Start working on this @Bhavika-14

**Comment by Vikash-8090-Yadav** [comment]
@Bhavika-14 if this issue is solved then please close this Issue as completed !!

**Comment by Chinmay-Deo-2004** [comment]
@Vikash-8090-Yadav 
If @Bhavika-14 isn't presently able to work on this issue, please assign it to me.

**Comment by Bhavika-14** [comment]
#10

**Comment by Bhavika-14** [comment]
> @Bhavika-14 if this issue is solved then please close this Issue as completed !!

Yes, it is completed.  #10
