### ISSUE TITLE
Improvement in UI by making several css changes 

### ISSUE THREAD

**Issue by raghav1030** [Vikash-8090-Yadav/SaL--dApp#70]
The changes are mostly related to  : 

Button : we can add color changing property when the button gets hovered upon. It makes the design look more modern.

scrollbar : adding css to the scrollbars to make the website look more pretty.

and many other small changes that can make the the UI better.

So if you want I would like to do the task.

And this is related to Gssoc'23

**Comment by Vikash-8090-Yadav** [comment]
Please share the images for the same.

**Comment by raghav1030** [comment]
We can change the css of the scrollbar and add some transition on the the dropdown list for "Select Profile option"
![Dapp eth-scrollbars](https://github.com/Vikash-8090-Yadav/SaL--dApp/assets/94848646/a453a809-0fd1-4bde-aba7-8a81f21d60ba)

**Comment by Vikash-8090-Yadav** [comment]
Great start working on this.
