### ISSUE TITLE
Data button Non-responsive

### ISSUE THREAD

**Issue by mohitvdx** [Vikash-8090-Yadav/SaL--dApp#71]
**Data** button on the landing page header is not responding.

<img width="1440" alt="Screenshot 2023-05-22 at 5 34 53 PM" src="https://github.com/Vikash-8090-Yadav/SaL--dApp/assets/112820522/263cfa6d-33d6-401f-bb0b-85851a1d929a">

Highlighted with a _Red box_ in the above image.

**Comment by Vikash-8090-Yadav** [comment]
Great linked data  to the main section which is just below the hero section.
