### ISSUE TITLE
Add contrubution section  just above the project contributor (member) part 

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/SaL--dApp#72]
Take
![Screenshot from 2023-05-22 19-55-17](https://github.com/Vikash-8090-Yadav/SaL--dApp/assets/85225156/f395bd1e-7088-4006-8b3a-18f89b0a1dab)
 help from this repo.   https://github.com/Vikash-8090-Yadav/Future.WebNet

**Comment by Deepanshu-Sharma-18** [comment]
@Vikash-8090-Yadav Can I work on this quick?

**Comment by iasadk** [comment]
I have Raised The PR for Updated README.md file 
[Click here to go to PR](https://github.com/Vikash-8090-Yadav/SaL--dApp/pull/76)
