### ISSUE TITLE
Add logout on the navbar

### ISSUE THREAD

**Issue by Vikash-8090-Yadav** [Vikash-8090-Yadav/SaL--dApp#8]
Add the logout button on the nav bar

**Comment by Joseph2001-braganza** [comment]
Hi @Vikash-8090-Yadav I would like to contribute to this issue.

**Comment by Vikash-8090-Yadav** [comment]
> Hi @Vikash-8090-Yadav I would like to contribute to this issue.

Sure , start working on this

**Comment by Joseph2001-braganza** [comment]
![image](https://user-images.githubusercontent.com/77545228/226929042-83ee4a29-19fe-4df9-9c19-88693e539c0b.png)
Added the Logout Button. 
Can I commit the changes.

**Comment by Joseph2001-braganza** [comment]
I have Created a Pull Request.

**Comment by Joseph2001-braganza** [comment]
Hi @Vikash-8090-Yadav I have updated the Logout button you can check my pull request.
