### ISSUE TITLE
Adding the onlyOwner functionality to the addemp function.

### ISSUE THREAD

**Issue by KritikaJoshi22** [Vikash-8090-Yadav/SaL--dApp#82]
Anyone can add an employ details in the addemp function and this can result in fake accounts or might pose other security risks.

**Comment by KritikaJoshi22** [comment]
@Vikash-8090-Yadav  please assign me this issue under GSSoC. I wanna work on this.

**Comment by Vikash-8090-Yadav** [comment]
Hey @KritikaJoshi22 thanks but it's already opened issue. PLease chk once.

**Comment by Vikash-8090-Yadav** [comment]
Feel free to open this , if u can't find
