### ISSUE TITLE
Add section-wise 'back-to-top' links in ReadMe.md

### ISSUE THREAD

**Issue by VSatwika** [Vikash-8090-Yadav/SaL--dApp#97]
- ReadMe.md file is quite lengthy. So adding back to links at the end of every section will improve the navigation and ease of use.
 - I would like to work on this. Could this be assigned to me @Vikash-8090-Yadav under GSSoC'23.
   Thank you

**Comment by Vikash-8090-Yadav** [comment]
Great .
